(() => {
"use strict";
const APPS_SCRIPT_URL="https://script.google.com/macros/s/AKfycbzDrLyFEsCVSVqLphU7fiCrNo_slakHFf6R8JSHvqT-5Lr6Y5uxyBQbNshS0uzUXSHa/exec";
const menuBtn=document.getElementById("menuBtn"),mobileNav=document.getElementById("mobileNav");
if(menuBtn&&mobileNav){menuBtn.addEventListener("click",()=>{const open=mobileNav.classList.toggle("open");menuBtn.setAttribute("aria-expanded",String(open));menuBtn.setAttribute("aria-label",open?"Menü schließen":"Menü öffnen")});mobileNav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{mobileNav.classList.remove("open");menuBtn.setAttribute("aria-expanded","false")}))}
document.querySelectorAll("[data-scroll-demo]").forEach(btn=>btn.addEventListener("click",()=>document.getElementById("demo")?.scrollIntoView({behavior:"smooth",block:"start"})));
const demoMessages=document.getElementById("demoMessages"),demoInput=document.getElementById("demoInput"),demoForm=document.getElementById("demoForm");
const answers=[{keys:["kosten","preis","preise"],answer:"Cora Basic kostet 895 € einmalig + 495 € monatlich. Cora Pro kostet 1.495 € einmalig + 895 € monatlich. Enterprise wird individuell kalkuliert."},{keys:["lead","anfrage","kontakt"],answer:"Ja. Cora kann Besucher durch relevante Fragen führen und – je nach vereinbartem Setup – Kontaktdaten und Anliegen strukturiert aufnehmen."},{keys:["einrichtung","integration","website","install"],answer:"Die technische Einbindung wird an Ihre bestehende Website angepasst. Im Setup werden Inhalte, Tonalität, Gesprächsführung und der gewünschte Lead-Prozess festgelegt."},{keys:["unternehmen","für wen","branche","geeignet"],answer:"Cora eignet sich besonders für Unternehmen mit wiederkehrenden Website-Fragen und erklärungsbedürftigen Leistungen – etwa Mittelstand, Dienstleister, Handwerk, Hotels, Restaurants, Immobilien und Beratung."},{keys:["datenschutz","dsgvo","daten"],answer:"Datenschutz wird im jeweiligen Einsatzfall berücksichtigt. Entscheidend sind unter anderem die verarbeiteten Daten, Anbieter, Speicherorte, Auftragsverarbeitung und die konkrete technische Einbindung."}];
function getAnswer(q){const hit=answers.find(item=>item.keys.some(k=>q.toLowerCase().includes(k)));return hit?hit.answer:"Das hängt vom konkreten Einsatzfall ab. Cora kann Fragen zu Leistungen, Abläufen und häufigen Anliegen beantworten und Interessenten – je nach Konfiguration – zur passenden Anfrage führen."}
function addDemoMessage(text,type){if(!demoMessages)return;const el=document.createElement("div");el.className="msg "+type;el.textContent=text;demoMessages.appendChild(el);demoMessages.scrollTop=demoMessages.scrollHeight}
function runDemo(q){q=String(q||"").trim();if(!q||!demoMessages)return;addDemoMessage(q,"user");setTimeout(()=>addDemoMessage(getAnswer(q),"cora"),420)}
document.querySelectorAll("[data-prompt]").forEach(btn=>btn.addEventListener("click",()=>runDemo(btn.dataset.prompt)));
demoForm?.addEventListener("submit",e=>{e.preventDefault();const value=demoInput?.value||"";if(!value.trim())return;runDemo(value);demoInput.value="";demoInput.focus()});
const leadForm=document.getElementById("leadForm"),status=document.getElementById("formStatus");
leadForm?.addEventListener("submit",async e=>{e.preventDefault();if(!leadForm.reportValidity())return;const hp=leadForm.querySelector('[name="website_check"]');if(hp?.value)return;const button=leadForm.querySelector('button[type="submit"]'),original=button?.innerHTML;if(button){button.disabled=true;button.innerHTML="Wird übermittelt …"}if(status){status.className="form-status";status.textContent=""}const data=new URLSearchParams();new FormData(leadForm).forEach((value,key)=>data.append(key,String(value)));data.append("source","Cora Website");data.append("page",window.location.href);data.append("submitted_at_client",new Date().toISOString());
try{await fetch(APPS_SCRIPT_URL,{method:"POST",mode:"no-cors",body:data});leadForm.reset();if(status){status.className="form-status success";status.textContent="Ihre Anfrage wurde übermittelt. Vielen Dank."}}catch(error){console.error(error);if(status){status.className="form-status error";status.textContent="Die Anfrage konnte gerade nicht übermittelt werden. Bitte versuchen Sie es erneut."}}finally{if(button){button.disabled=false;button.innerHTML=original||"Cora anfragen"}}});
})();